import type { Metadata } from "next";
import "../styles/main.css"
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Cinemorra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
        </body>
    </html>
  );
}
